name: Scan Pull Request

on:
  pull_request:
    branches:
      - dev

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: python -m pytest --junitxml results.xml

      - name: Upload test results
        uses: actions/upload-artifact@master
        with:
          name: Test results - ${{ matrix.python-version }}
          path: results.xml

      - name: Run linter
        uses: chartboost/ruff-action@v1
